name: NotepadPy++ Build

on:
    push:
        branches: [master]

jobs:
    testing:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install QT (Ubuntu)
              uses: jurplel/install-qt-action@v4
              if: runner.os == 'Linux'
              with:
                version: '6.8.0'
                host: 'linux'
                target: 'desktop'
                arch: 'linux_gcc_64'
                install-deps: 'true'

            - name: Install QT (Windows)
              uses: jurplel/install-qt-action@v4
              if: runner.os == 'Windows'
              with:
                version: '6.8.0'
                host: 'windows'
                target: 'desktop'
                arch: 'win64_msvc2022_64'
                install-deps: 'true'
                
            - name: Build executable
              run: |
                pip install -r src/notepadpypp/requirements.txt
                pip install pyinstaller
                pyinstaller main.spec

            - name: Compress (Windows)
              if: runner.os == 'Windows'
              run: |
                mkdir release
                move dist\* release\
                tar -a -c -f NotepadPypp-Windows-amd64.zip release
             
            - name: Compress (Linux)
              if: runner.os == 'Linux'
              run: |
                mkdir release
                mv dist/* release/
                tar -czvf NotepadPypp-Linux-amd64.tar.gz release
            
            - name: Upload release (Windows)
              if: runner.os == 'Windows'
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: NotepadPypp-Windows-amd64.zip
                asset_name: NotepadPypp-Windows-amd64.zip
                tag: nppypp-prototype
                prerelease: true
                overwrite: true
            
            - name: Upload release (Linux)
              if: runner.os == 'Linux'
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: 'NotepadPypp-Linux-amd64.tar.gz'
                asset_name: NotepadPypp-Linux-amd64.tar.gz
                tag: nppypp-prototype
                prerelease: true
                overwrite: true