name: NotepadPy++ Build

on:
    push:
        branches: [master]

jobs:
    testing:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install QT (Ubuntu)
              uses: jurplel/install-qt-action@v4
              if: runner.os == 'Linux'
              with:
                version: '6.8.0'
                host: 'linux'
                target: 'desktop'
                arch: 'linux_gcc_64'
                install-deps: 'true'

            - name: Install QT (Windows)
              uses: jurplel/install-qt-action@v4
              if: runner.os == 'Windows'
              with:
                version: '6.8.0'
                host: 'windows'
                target: 'desktop'
                arch: 'win64_msvc2022_64'
                install-deps: 'true'
                
            - name: Build executable
              run: |
                pip install -r src/notepadpypp/requirements.txt
                pip install pyinstaller
                pyinstaller main.spec
            
            - name: Debug why the hell its not including the Qsci hook (Linux)
              if: runner.os == 'Linux'
              run: | 
                ls /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/PyInstaller/hooks
            
            - name: Debug why the hell its not including the Qsci hook (Windows)
              if: runner.os == 'Windows'
              run: | 
                dir C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64\\Lib\\site-packages\\PyInstaller\\hooks