name: NotepadPy++ Build

on:
    push:
        branches: [master]

jobs:
    testing:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install QT (Ubuntu)
              uses: jurplel/install-qt-action@v4
              if: runner.os == 'Linux'
              with:
                version: '6.8.0'
                host: 'linux'
                target: 'desktop'
                arch: 'linux_gcc_64'
                install-deps: 'true'

            - name: Install QT (Windows)
              uses: jurplel/install-qt-action@v4
              if: runner.os == 'Windows'
              with:
                version: '6.8.0'
                host: 'windows'
                target: 'desktop'
                arch: 'win64_msvc2022_64'
                install-deps: 'true'
                
            - name: Setup and run pyinstaller
              run: |
                pip install PyQt6 PyQt6.Qsci
                pip install pyinstaller
                pyinstaller --onefile --name "NotepadPyqq" src/notepadpypp/main.py --hidden-import=PyQt6.Qsci